//
//  AlbumsPresenter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 28/07/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AlbumsPresentationLogic {
	func presentSomething(response: Albums.Something.Response)
}

class AlbumsPresenter: AlbumsPresentationLogic {
	weak var viewController: AlbumsDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: Albums.Something.Response) {
		let viewModel = Albums.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
