//
//  FullPhotoInteractor.swift
//  PhotosApp
//
//  Created by Allison Lindner on 04/08/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullPhotoBusinessLogic {
	func loadImage(request: FullPhoto.Image.Request)
}

protocol FullPhotoDataStore {
	var photoURL: String { get set }
}

class FullPhotoInteractor: FullPhotoBusinessLogic, FullPhotoDataStore {
	var presenter: FullPhotoPresentationLogic?
	var worker: FullPhotoWorker?
	var photoURL: String = ""
	
	// MARK: Do something
	
	func loadImage(request: FullPhoto.Image.Request) {
		if let url = URL(string: self.photoURL) {
			let data = try! Data(contentsOf: url)
			let image = UIImage(data : data)!
			
			let response = FullPhoto.Image.Response(image: image)
			presenter?.presentImage(response: response)
		}
	}
}
