//
//  FullPhotoRouter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 04/08/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FullPhotoRoutingLogic {
	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FullPhotoDataPassing {
	var dataStore: FullPhotoDataStore? { get }
}

class FullPhotoRouter: NSObject, FullPhotoRoutingLogic, FullPhotoDataPassing {
	weak var viewController: FullPhotoViewController?
	var dataStore: FullPhotoDataStore?
	
	// MARK: Routing
	
	//func routeToSomewhere(segue: UIStoryboardSegue?)
	//{
	//  if let segue = segue {
	//    let destinationVC = segue.destination as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//  } else {
	//    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	//    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//    navigateToSomewhere(source: viewController!, destination: destinationVC)
	//  }
	//}
	
	// MARK: Navigation
	
	//func navigateToSomewhere(source: FullPhotoViewController, destination: SomewhereViewController)
	//{
	//  source.show(destination, sender: nil)
	//}
	
	// MARK: Passing data
	
	//func passDataToSomewhere(source: FullPhotoDataStore, destination: inout SomewhereDataStore)
	//{
	//  destination.name = source.name
	//}
}
