//
//  FullPhotoInteractor.swift
//  PhotosApp
//
//  Created by Allison Lindner on 04/08/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullPhotoBusinessLogic
{
  func doSomething(request: FullPhoto.Something.Request)
}

protocol FullPhotoDataStore
{
  //var name: String { get set }
}

class FullPhotoInteractor: FullPhotoBusinessLogic, FullPhotoDataStore
{
  var presenter: FullPhotoPresentationLogic?
  var worker: FullPhotoWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FullPhoto.Something.Request)
  {
    worker = FullPhotoWorker()
    worker?.doSomeWork()
    
    let response = FullPhoto.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
