//
//  FullPhotoPresenter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 04/08/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FullPhotoPresentationLogic
{
  func presentSomething(response: FullPhoto.Something.Response)
}

class FullPhotoPresenter: FullPhotoPresentationLogic
{
  weak var viewController: FullPhotoDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FullPhoto.Something.Response)
  {
    let viewModel = FullPhoto.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
