//
//  FullPhotoModels.swift
//  PhotosApp
//
//  Created by Allison Lindner on 04/08/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FullPhoto {
	// MARK: Use cases
	
	enum Image {
		struct Request {
		}
		struct Response {
			var image: UIImage
		}
		struct ViewModel {
			var image: UIImage
		}
	}
}
