//
//  PhotosPresenter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 28/07/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotosPresentationLogic {
	func presentPhotos(response: Photos.Data.Response)
	func presentFullPhoto(response: Photos.Full.Response)
}

class PhotosPresenter: PhotosPresentationLogic {
	var viewController: PhotosDisplayLogic?
	
	// MARK: Do something
	
	func presentPhotos(response: Photos.Data.Response) {
		let viewModel = Photos.Data.ViewModel(photosId: response.photosId, images: response.images)
		viewController?.displayPhotos(viewModel: viewModel)
	}
	
	func presentFullPhoto(response: Photos.Full.Response) {
		let viewModel = Photos.Full.ViewModel(url: response.url)
		viewController?.displayFullPhoto(viewModel: viewModel)
	}
}
