//
//  PhotosRouter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 28/07/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhotosRoutingLogic {
	func routeToFullPhoto(segue: UIStoryboardSegue?)
}

protocol PhotosDataPassing {
	var dataStore: PhotosDataStore? { get }
}

class PhotosRouter: NSObject, PhotosRoutingLogic, PhotosDataPassing {
	weak var viewController: PhotosViewController?
	var dataStore: PhotosDataStore?
	
	// MARK: Routing
	
	func routeToFullPhoto(segue: UIStoryboardSegue?) {
		if let segue = segue {
			let destinationVC = segue.destination as! FullPhotoViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToFullPhoto(source: dataStore!, destination: &destinationDS)
		}
	}
	
	// MARK: Passing data
	
	func passDataToFullPhoto(source: PhotosDataStore, destination: inout FullPhotoDataStore) {
		destination.photoURL = source.photoURL
	}
}
