//
//  PhotosModels.swift
//  PhotosApp
//
//  Created by Allison Lindner on 28/07/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Photos {
	// MARK: Use cases
	
	enum Data {
		struct Request {
			var count: Int
		}
		struct Response {
			var photosId: [Int:Int]
			var images: [Int:UIImage]
		}
		struct ViewModel {
			var photosId: [Int:Int]
			var images: [Int:UIImage]
		}
	}
	
	enum Full {
		struct Request {
			var id: Int
		}
		struct Response {
			var url: String
		}
		struct ViewModel {
			var url: String
		}
	}
}
