//
//  SplashPresenter.swift
//  PhotosApp
//
//  Created by Allison Lindner on 31/07/20.
//  Copyright (c) 2020 Allison Lindner. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashPresentationLogic {
	func presentFetchDataResult(response: Splash.Fetch.Response)
}

class SplashPresenter: SplashPresentationLogic {
	weak var viewController: SplashDisplayLogic?
	
	// MARK: Do something
	
	func presentFetchDataResult(response: Splash.Fetch.Response) {
		let viewModel = Splash.Fetch.ViewModel(result: false)
		viewController?.displayFetchDataResult(viewModel: viewModel)
	}
}
